# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/emilien/Epitech/semestre4/oop/Arcade/B-OOP-400-LYN-4-1-arcade-marvin.flamand

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/emilien/Epitech/semestre4/oop/Arcade/B-OOP-400-LYN-4-1-arcade-marvin.flamand

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/emilien/Epitech/semestre4/oop/Arcade/B-OOP-400-LYN-4-1-arcade-marvin.flamand/CMakeFiles /home/emilien/Epitech/semestre4/oop/Arcade/B-OOP-400-LYN-4-1-arcade-marvin.flamand//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/emilien/Epitech/semestre4/oop/Arcade/B-OOP-400-LYN-4-1-arcade-marvin.flamand/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arcade

# Build rule for target.
arcade: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arcade
.PHONY : arcade

# fast build rule for target.
arcade/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/build
.PHONY : arcade/fast

#=============================================================================
# Target rules for targets named nibbler

# Build rule for target.
nibbler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nibbler
.PHONY : nibbler

# fast build rule for target.
nibbler/fast:
	$(MAKE) $(MAKESILENT) -f lib/games/nibbler/CMakeFiles/nibbler.dir/build.make lib/games/nibbler/CMakeFiles/nibbler.dir/build
.PHONY : nibbler/fast

#=============================================================================
# Target rules for targets named centipede

# Build rule for target.
centipede: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 centipede
.PHONY : centipede

# fast build rule for target.
centipede/fast:
	$(MAKE) $(MAKESILENT) -f lib/games/centipede/CMakeFiles/centipede.dir/build.make lib/games/centipede/CMakeFiles/centipede.dir/build
.PHONY : centipede/fast

#=============================================================================
# Target rules for targets named menu

# Build rule for target.
menu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 menu
.PHONY : menu

# fast build rule for target.
menu/fast:
	$(MAKE) $(MAKESILENT) -f lib/games/menu/CMakeFiles/menu.dir/build.make lib/games/menu/CMakeFiles/menu.dir/build
.PHONY : menu/fast

#=============================================================================
# Target rules for targets named ncurses

# Build rule for target.
ncurses: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ncurses
.PHONY : ncurses

# fast build rule for target.
ncurses/fast:
	$(MAKE) $(MAKESILENT) -f lib/graphics/ncurses/CMakeFiles/ncurses.dir/build.make lib/graphics/ncurses/CMakeFiles/ncurses.dir/build
.PHONY : ncurses/fast

#=============================================================================
# Target rules for targets named sfml

# Build rule for target.
sfml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml
.PHONY : sfml

# fast build rule for target.
sfml/fast:
	$(MAKE) $(MAKESILENT) -f lib/graphics/sfml/CMakeFiles/sfml.dir/build.make lib/graphics/sfml/CMakeFiles/sfml.dir/build
.PHONY : sfml/fast

#=============================================================================
# Target rules for targets named sdl2

# Build rule for target.
sdl2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl2
.PHONY : sdl2

# fast build rule for target.
sdl2/fast:
	$(MAKE) $(MAKESILENT) -f lib/graphics/sdl2/CMakeFiles/sdl2.dir/build.make lib/graphics/sdl2/CMakeFiles/sdl2.dir/build
.PHONY : sdl2/fast

src/Core.o: src/Core.cpp.o
.PHONY : src/Core.o

# target to build an object file
src/Core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/Core.cpp.o
.PHONY : src/Core.cpp.o

src/Core.i: src/Core.cpp.i
.PHONY : src/Core.i

# target to preprocess a source file
src/Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/Core.cpp.i
.PHONY : src/Core.cpp.i

src/Core.s: src/Core.cpp.s
.PHONY : src/Core.s

# target to generate assembly for a file
src/Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/Core.cpp.s
.PHONY : src/Core.cpp.s

src/Error.o: src/Error.cpp.o
.PHONY : src/Error.o

# target to build an object file
src/Error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/Error.cpp.o
.PHONY : src/Error.cpp.o

src/Error.i: src/Error.cpp.i
.PHONY : src/Error.i

# target to preprocess a source file
src/Error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/Error.cpp.i
.PHONY : src/Error.cpp.i

src/Error.s: src/Error.cpp.s
.PHONY : src/Error.s

# target to generate assembly for a file
src/Error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/Error.cpp.s
.PHONY : src/Error.cpp.s

src/Utils/FileParser.o: src/Utils/FileParser.cpp.o
.PHONY : src/Utils/FileParser.o

# target to build an object file
src/Utils/FileParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/Utils/FileParser.cpp.o
.PHONY : src/Utils/FileParser.cpp.o

src/Utils/FileParser.i: src/Utils/FileParser.cpp.i
.PHONY : src/Utils/FileParser.i

# target to preprocess a source file
src/Utils/FileParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/Utils/FileParser.cpp.i
.PHONY : src/Utils/FileParser.cpp.i

src/Utils/FileParser.s: src/Utils/FileParser.cpp.s
.PHONY : src/Utils/FileParser.s

# target to generate assembly for a file
src/Utils/FileParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/Utils/FileParser.cpp.s
.PHONY : src/Utils/FileParser.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... arcade"
	@echo "... centipede"
	@echo "... menu"
	@echo "... ncurses"
	@echo "... nibbler"
	@echo "... sdl2"
	@echo "... sfml"
	@echo "... src/Core.o"
	@echo "... src/Core.i"
	@echo "... src/Core.s"
	@echo "... src/Error.o"
	@echo "... src/Error.i"
	@echo "... src/Error.s"
	@echo "... src/Utils/FileParser.o"
	@echo "... src/Utils/FileParser.i"
	@echo "... src/Utils/FileParser.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

