#pragma once

#include "IDisplayModule.hpp"
#include <fcntl.h>
#include <fstream>
#include <ncurses.h>

class Ncurses : public arc::display::IDisplayModule {
        public:
            Ncurses();
            ~Ncurses();

            /**
             * @brief draw all the objects generated by the game
             *
             * @param objs
             */
            void drawObjects(std::vector<std::shared_ptr<arc::Object>> objs);

            /**
             * @brief get any event
             *
             * @return const arc::Events
             */
            const arc::Events getEvent() const;
    };