#pragma once

#include "Interfaces/IDisplayModule.hpp"
#include <fcntl.h>
#include <fstream>
#include <ncurses.h>

namespace arc::display {
class NcursesDisplay : public arc::display::IDisplayModule {
        public:
            NcursesDisplay();
            ~NcursesDisplay();

            /**
             * @brief draw all the objects generated by the game
             *
             * @param objs
             */
            void drawObjects(std::vector<std::shared_ptr<arc::Object>> objs) override;

            /**
             * @brief get any event
             *
             * @return const arc::Events
             */
            arc::Events getEvent() const override;

            /**
             * @brief Draw the interface of the game
             *
             */
            void drawInterface(std::vector<std::shared_ptr<arc::Object>> objs);

        private:
            const char* getTexture(const std::string fileName);
    };
}