#include <Interfaces/IDisplayModule.hpp>

#include <SDL2/SDL.h>

#pragma once


namespace arc::display {

    class Sdl2Display : public IDisplayModule {
        public:
            /**
             * @brief Create a new Sdl2Display object
             *
             */
            Sdl2Display();

            /**
             * @brief Destroy a Sld2Display object
             *
             */
             ~Sdl2Display();

             /**
              * @brief Draw all the objects generated by the game
              *
              * @param objs objects to be drawn
              */
             void drawObjects(std::vector<std::shared_ptr<arc::Object>> objs) override;

             /**
              * @brief Get any event
              *
              * @return const arc::Events - event that occured (or arc::Events::NONE)
              */
            arc::Events getEvent() const override;

        private:
            /**
             * @brief SDL window
             *
             */
            SDL_Window *m_window;

            /**
             * @brief SDL renderer
             *
             */
            SDL_Renderer *m_renderer;

    }; /* class Sdl2Display */

}; /* namespace arc::display */
