#include <Interfaces/IDisplayModule.hpp>

#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include <map>

#pragma once


namespace arc::display {

    class Sdl2Display : public IDisplayModule {
        public:
            /**
             * @brief Create a new Sdl2Display object
             *
             */
            Sdl2Display();

            /**
             * @brief Destroy a Sld2Display object
             *
             */
             ~Sdl2Display();

             /**
              * @brief Draw all the objects generated by the game
              *
              * @param objs objects to be drawn
              */
             void drawObjects(std::vector<std::shared_ptr<arc::Object>> objs) override;

            /**
             * @brief Draw the interface of the game
             *
             * @param objs objects to be drawn
             */
            void drawInterface(std::vector<std::shared_ptr<arc::Object>> objs) override;

             /**
              * @brief Get any event
              *
              * @return const arc::Events - event that occured (or arc::Events::NONE)
              */
            arc::Events getEvent() const override;

            /**
             * @brief Place an object on the board
             *
             * @param obj object to be placed
             */
            void placeObjectOnBoard(std::shared_ptr<arc::Object> obj);

        private:

            /**
             * @brief Get a texture by name
             *
             * @param name name of the texture
             * @return SDL_Texture*
             */
            SDL_Texture *getTexture(const std::string& name);

            /**
             * @brief Draw an object of type SPRITE
             *
             * @param obj object to draw
             */
            void drawSprite(std::shared_ptr<arc::Object> obj);

            /**
             * @brief Draw an object of type TEXT
             *
             * @param obj
             */
            void drawText(std::shared_ptr<arc::Object> obj);

            /**
             * @brief SDL window
             *
             */
            SDL_Window *m_window;

            /**
             * @brief SDL renderer
             *
             */
            SDL_Renderer *m_renderer;

            /**
             * @brief Loaded textures
             *
             */
            std::map<std::string, SDL_Texture*> m_textures;

            /**
             * @brief Interpret SDL2 Keyboard events
             *
             * @param event SDL2 Keyboard event
             */
            arc::Events interpretKeyboardEvent(const SDL_KeyboardEvent& event) const;

    }; /* class Sdl2Display */

}; /* namespace arc::display */
